import string
import re
import argparse
import json
import sys
from collections import Counter

def normalize_answer(s):
    """Lower text and remove punctuation, articles and extra whitespace."""
    def remove_articles(text):
        return re.sub(r'\b(a|an|the)\b', ' ', text)
    def white_space_fix(text):
        return ' '.join(text.split())
    def remove_punc(text):
        exclude = set(string.punctuation)
        return ''.join(ch for ch in text if ch not in exclude)
    def lower(text):
        return text.lower()
    return white_space_fix(remove_articles(remove_punc(lower(str(s)))))

def f1_score(prediction, ground_truth):
    prediction_tokens = normalize_answer(prediction).split()
    ground_truth_tokens = normalize_answer(ground_truth).split()
    common = Counter(prediction_tokens) & Counter(ground_truth_tokens)
    num_same = sum(common.values())
    if num_same == 0:
        return 0
    precision = 1.0 * num_same / len(prediction_tokens)
    recall = 1.0 * num_same / len(ground_truth_tokens)
    return (2 * precision * recall) / (precision + recall)

def exact_match_score(prediction, ground_truth):
    return (normalize_answer(prediction) == normalize_answer(ground_truth))

def metric_max_over_ground_truths(metric_fn, prediction, ground_truths):
    scores_for_ground_truths = []
    for ground_truth in ground_truths:
        score = metric_fn(prediction, ground_truth)
        scores_for_ground_truths.append(score)
    return max(scores_for_ground_truths)

def evaluate(dataset, predictions, contexts):
    f1 = exact_match = recall_hits = total = 0
    
    # We assume standard SQuAD formatting generated by prep_reference.py
    qas = dataset[0]['paragraphs'][0]['qas']
    
    for i, qa in enumerate(qas):
        total += 1
        ground_truths = list(map(lambda x: x['text'], qa['answers']))
        prediction = predictions.get(qa['id'], "")
        
        exact_match += metric_max_over_ground_truths(exact_match_score, prediction, ground_truths)
        f1 += metric_max_over_ground_truths(f1_score, prediction, ground_truths)
        
        # Recall Logic: Check if ANY ground truth is inside the retrieved context
        if i < len(contexts):
            norm_context = normalize_answer(contexts[i])
            for gt in ground_truths:
                if normalize_answer(gt) in norm_context:
                    recall_hits += 1
                    break # Found it, move to next question

    exact_match = 100.0 * exact_match / total
    f1 = 100.0 * f1 / total
    recall = 100.0 * recall_hits / total

    return {'exact_match': exact_match, 'f1': f1, 'recall': recall}

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('dataset_file', help='Ground truth JSON')
    parser.add_argument('prediction_file', help='Prediction JSON')
    parser.add_argument('context_file', help='Retrieved contexts TXT')
    args = parser.parse_args()
    
    with open(args.dataset_file) as dataset_file:
        dataset = json.load(dataset_file)['data']
    with open(args.prediction_file) as prediction_file:
        predictions = json.load(prediction_file)
    with open(args.context_file) as context_file:
        contexts = [line.strip() for line in context_file.readlines()]
        
    results = evaluate(dataset, predictions, contexts)
    print("\n=== RAG System Performance ===")
    print(f"Exact Match: {results['exact_match']:.2f}%")
    print(f"F1 Score:    {results['f1']:.2f}%")
    print(f"Recall:      {results['recall']:.2f}%")
    print("==============================\n")