import json

def load_jsonl(filepath):
    data = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            data.append(json.loads(line.strip()))
    return data

def prep_files(jsonl_path):
    data = load_jsonl(jsonl_path)
    
    # 1. Extract questions for main.py
    with open('questions.txt', 'w', encoding='utf-8') as f:
        for item in data:
            f.write(f"{item['question']}\n")
            
    # 2. Format ground truth for SQuAD evaluation script
    squad_data = {
        "version": "1.1",
        "data": [{
            "title": "EECS_Reference",
            "paragraphs": [{
                "context": "",
                "qas": []
            }]
        }]
    }
    
    for i, item in enumerate(data):
        # The staff uses "answer" (singular)
        raw_answer = str(item['answer'])
        
        # SQuAD needs a list of answer dictionaries. 
        # If they provided multiple valid answers separated by '|', we split them.
        if '|' in raw_answer:
            ans_list = [{"text": a.strip(), "answer_start": 0} for a in raw_answer.split('|')]
        else:
            ans_list = [{"text": raw_answer.strip(), "answer_start": 0}]

        # Match the ID format generated by converter.py (q1, q2, q3...)
        q_id = f"q{i+1}"
        
        qas_entry = {
            "answers": ans_list,
            "question": item['question'],
            "id": q_id
        }
        squad_data["data"][0]["paragraphs"][0]["qas"].append(qas_entry)
        
    with open('squad_ground_truth.json', 'w', encoding='utf-8') as f:
        json.dump(squad_data, f, indent=4)
        
    print(f"✅ Processed {len(data)} items from {jsonl_path}")
    print("✅ Created: questions.txt (for RAG input)")
    print("✅ Created: squad_ground_truth.json (for evaluation)")

if __name__ == "__main__":
    prep_files('reference.jsonl')